export const translations = {
  en: {
    // Header
    shopBtn: 'Shop Products →',

    // Progress steps
    stepSport:   'Sport',
    stepEvent:   'Event',
    stepSplits:  'Splits',
    stepBody:    'Body',
    stepSweat:   'Sweat Profile',
    stepContact: 'Contact',
    stepPlan:    'Your Plan',

    // Nav buttons
    back:     '← Back',
    continue: 'Continue →',
    next:     'Next →',

    // ── StepSport ─────────────────────────────────────────────────────────────
    sport_title:    'What sport are you planning for?',
    sport_subtitle: "We'll tailor your nutrition and hydration plan to your event.",
    sport_running:        'Running',
    sport_running_desc:   'Road, trail, track',
    sport_cycling:        'Cycling',
    sport_cycling_desc:   'Road, gravel, MTB',
    sport_triathlon:      'Triathlon',
    sport_triathlon_desc: 'Sprint to Ironman',
    sport_swimming:       'Swimming',
    sport_swimming_desc:  'Open water or pool',
    sport_other:          'Other',
    sport_other_desc:     'Team sports, CrossFit, etc.',

    // ── StepEvent ─────────────────────────────────────────────────────────────
    event_title:    "What's your event?",
    event_subtitle: 'Select your race distance, then pick your target pace.',
    event_group_road:      'Road Races',
    event_group_ultra:     'Ultra Running',
    event_group_trail:     'Trail Running',
    event_group_standard:  'Standard Formats',
    event_group_long:      'Long Course',
    event_group_granfondo: 'Gran Fondo / Road',
    event_group_race:      'Race Formats',
    event_group_ultra_cy:  'Ultra Cycling',
    event_group_openwater: 'Open Water',
    event_group_general:   'General Endurance',
    tier_beginner:         'Beginner',
    tier_beginner_desc:    'Comfortable pace, finish strong',
    tier_intermediate:     'Intermediate',
    tier_intermediate_desc:'Solid pacer, trained athlete',
    tier_advanced:         'Advanced',
    tier_advanced_desc:    'Competitive, racing to perform',
    event_finetune:        '⏱ Fine-tune your finish time',
    event_finetune_sub:    'Drag to match your expected pace. Range:',
    event_custom_title:    '✏️ Custom Event',
    event_custom_name:     'Event Name',
    event_custom_optional: '(optional)',
    event_custom_duration: 'Duration',
    event_custom_hours:    '(hours)',
    event_custom_distance: 'Distance',
    event_custom_km:       '(km, optional)',
    event_custom_back:     '← Back to event list',
    event_cant_find:       "Can't find your event?",
    event_custom_link:     'Enter custom event →',
    event_level_for:       "What's your level for",

    // ── StepSplits ────────────────────────────────────────────────────────────
    splits_title:      'Race Split Times',
    splits_subtitle:   'Enter your target finish time, then adjust each segment split.',
    splits_target:     'Your target finish time',
    splits_total:      'Splits total',
    splits_ok:         '✅ Perfectly matched to your race time!',
    splits_over:       'min over your target',
    splits_under:      'min under your target',

    // ── StepBody ──────────────────────────────────────────────────────────────
    body_title:       'About You',
    body_subtitle:    'Gender and age help us personalise carb, fluid, and sodium targets for your physiology.',
    body_gender:      'Gender',
    body_male:        'Male',
    body_male_desc:   'Higher sweat rate & carb needs on average',
    body_female:      'Female',
    body_female_desc: 'Lower baseline; hormonal cycle can affect needs',
    body_age:         'Age',
    body_age_unit:    'years',
    body_age_youth:   '🌱 Under 20: Growth phase — carb needs are higher relative to weight.',
    body_age_open:    '⚡ Age 20–34: Peak performance range. Baseline carb & fluid targets.',
    body_age_masters: '🏅 Age 35–49: Slightly reduced carb capacity. Recovery nutrition matters more.',
    body_age_senior:  '💪 Age 50+: Protein timing and electrolytes become more critical.',
    body_weight:      'Body Weight',
    body_weight_unit: 'kg',
    body_weight_hint: 'Used to scale carbohydrate targets via allometric formula (weight^0.75).',
    body_experience:  'Experience Level',
    body_beginner:    'Beginner',
    body_beginner_desc:     'First or second race',
    body_intermediate:      'Intermediate',
    body_intermediate_desc: '1–3 years racing',
    body_advanced:          'Advanced',
    body_advanced_desc:     '3+ years, regular competitor',

    // ── StepSweat ─────────────────────────────────────────────────────────────
    sweat_title:    'Your Sweat Profile',
    sweat_subtitle: 'This is the most personalised part of your plan. Sweat rate and saltiness determine your fluid and sodium needs.',
    sweat_analogy:  " Think of it like a car's fuel gauge — we need to know how fast your tank drains.",
    sweat_test_title: '🧪 Have your own sweat test data?',
    sweat_test_desc:  'If you\'ve done a sweat test (e.g. via Precision Hydration, Supersapiens, or a lab), enter your exact numbers for a more accurate plan.',
    sweat_test_btn:    'Enter test data',
    sweat_test_active: '✓ Using test data',
    sweat_rate_label:  'Sweat Rate',
    sweat_rate_unit:   'ml / hr',
    sweat_rate_hint:   'Measured as weight lost per hour of exercise (e.g. 1.2 kg/hr = 1200 ml/hr)',
    sweat_sodium_label: 'Sweat Sodium Concentration',
    sweat_sodium_unit:  'mg / L',
    sweat_sodium_hint:  'From a sweat patch or lab test. Typical range: 400–1800 mg/L.',
    sweat_override:     '· overridden by test data',
    sweat_level_q:   'How much do you typically sweat?',
    sweat_salt_q:    'How much sodium do you lose? (white residue on skin or kit)',
    sweat_fuel_q:    'What is your preferred nutrition ratio?',
    fuel_gel_label:  'Gels',
    fuel_gel_desc:   'Mostly gels and chews',
    fuel_mix_label:  'Mix (Gels & Drink Mix)',
    fuel_mix_desc:   'Balanced combination',
    fuel_liquid_label: 'Drink Mix',
    fuel_liquid_desc:  'Liquid calories prioritized',
    sweat_temp_q:    'Expected race temperature',
    sweat_low:       'Light sweater',        sweat_low_desc:      'Barely noticeable sweat even in heat',
    sweat_medium:    'Moderate sweater',     sweat_medium_desc:   'Visible sweat, slight wet patches',
    sweat_high:      'Heavy sweater',        sweat_high_desc:     'Dripping sweat, soaked shirt',
    sweat_very_high: 'Extreme sweater',      sweat_very_high_desc:'Puddles forming beneath you',
    salt_low:        'Light/no residue',     salt_low_desc:       'No white marks on skin or kit',
    salt_medium:     'Some white marks',     salt_medium_desc:    'Faint salt residue after long efforts',
    salt_high:       'Heavy salt residue',   salt_high_desc:      'Clear white crust on skin after sweating',
    salt_very_high:  'Very salty',           salt_very_high_desc: 'Burns eyes, heavy white crust everywhere',
    
    // Temperature
    temp_cold: '< 10°C', desc_cold: 'Very cold',
    temp_cool: '10–15°C', desc_cool: 'Cool',
    temp_mild: '15–20°C', desc_mild: 'Mild',
    temp_warm: '20–25°C', desc_warm: 'Warm',
    temp_hot: '25–30°C', desc_hot: 'Hot',
    temp_very_hot: '> 30°C', desc_very_hot: 'Very hot',

    sweat_test_success_1: 'Your plan will use',
    sweat_test_success_2: 'ml/hr sweat rate and',
    sweat_test_success_3: 'mg/L sodium.',


    // ── StepContact ───────────────────────────────────────────────────────────
    contact_title:    'Get Your Plan',
    contact_subtitle: 'Fill in your details to receive your personalised nutrition plan. Data is only used for support and is never shared with third parties.',
    contact_lastname:   'Last Name',
    contact_firstname:  'First Name',
    contact_email:      'Email',
    contact_phone:      'Phone',
    contact_optional:   'Optional',
    contact_privacy:    '🔒 Your information is secure and only used to provide your nutrition plan from HiBoost.',
    contact_submit:     '🚀 Generate My Plan →',
    contact_loading:    '⏳ Calculating...',
    contact_err_last:   'Please enter your last name',
    contact_err_first:  'Please enter your first name',
    contact_err_email:  'Please enter your email',
    contact_err_email2: 'Invalid email address',
    contact_err_phone:  'Invalid phone number',

    // ── Results ───────────────────────────────────────────────────────────────
    results_subtitle:   'YOUR PERSONALIZED RACE PLAN',
    results_new:        '↩ New Plan',
    results_carbs_hr:   'Carbs / hour',
    results_sodium_hr:  'Sodium / hour',
    results_fluid_hr:   'Fluid / hour',
    results_sweat_hr:   'Sweat rate / hour',
    results_estimated:  'estimated',
    results_from_test:  '🧪 from your test',
    results_segment:    '🏁 Segment Fuel Breakdown',
    results_segment_sub:'Nutrition targets for each part of your race.',
    results_no_fuel:    'No fuelling',
    results_timeline:   '⏱ Race Timeline',
    results_timeline_sub:'Checkpoints by segment — when and what to take.',
    results_products:   '🛒 Recommended Products',
    results_products_sub:'From the HiBoost catalog, matched to your plan.',
    results_no_products:'Short effort — water only, no products needed.',
    results_tips:       '💡 Key Tips for Your Plan',
    results_cta_title:  'Ready to race?',
    results_cta_desc:   'Shop all recommended products on HiBoost Nutrition.',
    results_cta_btn:    'Shop Now →',
    results_high_sodium_title: 'High Sodium Warning:',
    results_high_sodium_desc: 'Your target sodium intake is very high (>1000mg/h). Consistently consuming this much sodium can cause GI distress. Be sure to train your gut and consider supplementing with salt caps rather than just overly concentrated liquids.',
    results_disclaimer: '⚠️ This plan is generated based on population-average sports science formulas. Individual needs vary. Always test your nutrition strategy in training before race day. Consult a sports dietitian for medical or high-performance guidance.',
    results_total:      'total',
    nf_title:           'Nutrition Facts',
    nf_per_serving:     'per serving',
    nf_calories:        'Calories',
    nf_carbs:           'Carbs',
    nf_sodium:          'Sodium',
    nf_potassium:       'Potassium',
    nf_protein:         'Protein',
    nf_caffeine:        'Caffeine',

    // Cheat Sheet / Strategy Sticker
    sticker_title:      'Strategy Sticker',
    sticker_desc:       'Download a quick summary of your fuelling plan to stick on your top tube.',
    sticker_time:       'TIME',
    sticker_nutrition:  'NUTRITION',
    sticker_finish:     'BIKE FINISH',
    sticker_download:   '⬇️ Download PNG',

    // Cart / E-commerce
    cart_subtotal:      'Estimated Subtotal:',
    cart_order_btn:     '🛒 Order Request & Advice',
    cart_sending:       '⏳ Sending request...',
    cart_success:       '✅ Order request sent to HiBoost CRM. We will contact you soon!',

    // Usage keys
    usage_maurten_320:  'Mix 1 sachet (80g carbs) in 500ml. Sip slowly every 15 min.',
    usage_ph_powder:    'Mix 1 sachet in 500ml water. Continuous hydration & electrolytes.',
    usage_ph_gel:       'Take 1 gel every {interval} min. Do not take at the same time as Maurten 320.',
    usage_ph_gel_caf:   'Save for the final third of your race. Max 2–3 per event.',
    usage_pf90:         '90g carbs pouch for bike. 1 pouch lasts ~1.5h at 60g/hr.',
    usage_salt_caps:    'Take 1–2 caps with water every 30–45 min.',
    usage_maurten_gel:  'Premium gel option. Take 1 every {interval} min.',

    // Splits
    split_swim: 'Swim',
    split_t1:   'T1 (Transition)',
    split_bike: 'Bike',
    split_t2:   'T2 (Transition)',
    split_run:  'Run',

    // Tips keys from nutrition engine
    tip_female_fat_ox: 'Female athletes: oestrogen promotes fat oxidation — you may tolerate slightly lower carb intake than male athletes at same intensity.',
    tip_female_cycle: 'Hormonal cycle can affect heat tolerance and fluid retention. Track your training nutrition across your cycle.',
    tip_youth_growth: 'Youth athlete: your body needs more carbs relative to weight. Do not under-fuel — growth and recovery depend on adequate energy.',
    tip_masters_recovery: 'Masters athlete (35–49): prioritise recovery nutrition with protein within 30 min of finishing. Carb absorption is similar but recovery is slower.',
    tip_senior_electrolytes: '50+ athlete: electrolytes become more critical — kidneys are less efficient at retaining sodium. Do not skip salt capsules.',
    tip_senior_protein: 'Protein intake post-race is more important than for younger athletes. Aim for 30–40g protein within 1 hour of finishing.',
    tip_short_effort: 'Short effort under 45 min — water is sufficient. No carbs needed.',
    tip_high_carb_gut: 'High carb target: train your gut in long training sessions before race day to avoid GI issues.',
    tip_high_carb_mix: 'Use multiple carb sources (glucose + fructose) for better absorption above 60g/hr.',
    tip_salty_sweater: "High sodium target: you're a salty sweater. Do not skip electrolytes even in shorter efforts.",
    tip_hot_conditions: 'Hot conditions: start hydrating 2hrs before the race with 500ml water + electrolytes.',
    tip_pre_cooling: 'Pre-cooling strategies (ice vest, cold drink) can improve performance in heat.',
    tip_carb_load: 'For events 3+ hours: carb-load the 2 days before to maximize glycogen stores.',
    tip_practice_full: 'Practice your full race nutrition plan in at least 2 long training sessions.',
    tip_beginner_conservative: 'New to race nutrition? Start conservative — try half the carb target first, then increase.',

    // Footer
    footer: 'Based on ACSM & ISSN sports science guidelines',
  },

  vi: {
    // Header
    shopBtn: 'Mua Sản Phẩm →',

    // Progress steps
    stepSport:   'Môn',
    stepEvent:   'Sự Kiện',
    stepSplits:  'Phân Đoạn',
    stepBody:    'Cơ Thể',
    stepSweat:   'Mồ Hôi',
    stepContact: 'Liên Hệ',
    stepPlan:    'Kế Hoạch',

    // Nav buttons
    back:     '← Quay lại',
    continue: 'Tiếp theo →',
    next:     'Tiếp theo →',

    // ── StepSport ─────────────────────────────────────────────────────────────
    sport_title:    'Bạn đang chuẩn bị cho môn thể thao nào?',
    sport_subtitle: 'Chúng tôi sẽ tùy chỉnh kế hoạch dinh dưỡng và bổ sung nước cho sự kiện của bạn.',
    sport_running:        'Chạy Bộ',
    sport_running_desc:   'Đường bộ, trail, sân điền kinh',
    sport_cycling:        'Đạp Xe',
    sport_cycling_desc:   'Đường bộ, sỏi, địa hình',
    sport_triathlon:      'Ba Môn',
    sport_triathlon_desc: 'Sprint đến Ironman',
    sport_swimming:       'Bơi Lội',
    sport_swimming_desc:  'Nước mở hoặc bể bơi',
    sport_other:          'Khác',
    sport_other_desc:     'Thể thao đồng đội, CrossFit, v.v.',

    // ── StepEvent ─────────────────────────────────────────────────────────────
    event_title:    'Sự kiện của bạn là gì?',
    event_subtitle: 'Chọn cự ly đua, sau đó chọn tốc độ mục tiêu của bạn.',
    event_group_road:      'Đua Đường Bộ',
    event_group_ultra:     'Ultra Running',
    event_group_trail:     'Chạy Trail',
    event_group_standard:  'Cự Ly Chuẩn',
    event_group_long:      'Cự Ly Dài',
    event_group_granfondo: 'Gran Fondo / Đường Bộ',
    event_group_race:      'Các Hình Thức Đua',
    event_group_ultra_cy:  'Ultra Cycling',
    event_group_openwater: 'Bơi Nước Mở',
    event_group_general:   'Endurance Tổng Quát',
    tier_beginner:         'Người Mới',
    tier_beginner_desc:    'Tốc độ thoải mái, về đích mạnh mẽ',
    tier_intermediate:     'Trung Cấp',
    tier_intermediate_desc:'Vận động viên có kinh nghiệm',
    tier_advanced:         'Nâng Cao',
    tier_advanced_desc:    'Thi đấu cạnh tranh, chạy để thành tích',
    event_finetune:        '⏱ Điều chỉnh thời gian hoàn thành',
    event_finetune_sub:    'Kéo để khớp với tốc độ dự kiến. Khoảng:',
    event_custom_title:    '✏️ Sự Kiện Tùy Chỉnh',
    event_custom_name:     'Tên Sự Kiện',
    event_custom_optional: '(không bắt buộc)',
    event_custom_duration: 'Thời Gian',
    event_custom_hours:    '(giờ)',
    event_custom_distance: 'Cự Ly',
    event_custom_km:       '(km, không bắt buộc)',
    event_custom_back:     '← Quay lại danh sách',
    event_cant_find:       'Không tìm thấy sự kiện?',
    event_custom_link:     'Nhập sự kiện tùy chỉnh →',
    event_level_for:       'Trình độ của bạn cho',

    // ── StepSplits ────────────────────────────────────────────────────────────
    splits_title:    'Thời Gian Phân Đoạn',
    splits_subtitle: 'Nhập thời gian hoàn thành mục tiêu, sau đó điều chỉnh từng phân đoạn.',
    splits_target:   'Thời gian hoàn thành mục tiêu',
    splits_total:    'Tổng phân đoạn',
    splits_ok:       '✅ Khớp hoàn toàn với thời gian đua!',
    splits_over:     'phút vượt mục tiêu',
    splits_under:    'phút dưới mục tiêu',

    // ── StepBody ──────────────────────────────────────────────────────────────
    body_title:       'Thông Tin Cá Nhân',
    body_subtitle:    'Giới tính và tuổi giúp chúng tôi cá nhân hoá lượng carb, chất lỏng và natri cho cơ thể bạn.',
    body_gender:      'Giới Tính',
    body_male:        'Nam',
    body_male_desc:   'Tốc độ đổ mồ hôi và nhu cầu carb cao hơn',
    body_female:      'Nữ',
    body_female_desc: 'Nền tảng thấp hơn; chu kỳ nội tiết ảnh hưởng nhu cầu',
    body_age:         'Tuổi',
    body_age_unit:    'tuổi',
    body_age_youth:   '🌱 Dưới 20: Giai đoạn phát triển — nhu cầu carb tương đối cao hơn.',
    body_age_open:    '⚡ 20–34 tuổi: Đỉnh cao thể lực. Mục tiêu carb & nước chuẩn.',
    body_age_masters: '🏅 35–49 tuổi: Khả năng hấp thụ carb giảm nhẹ. Dinh dưỡng phục hồi quan trọng hơn.',
    body_age_senior:  '💪 50+ tuổi: Thời điểm bổ sung protein và điện giải trở nên quan trọng hơn.',
    body_weight:      'Cân Nặng',
    body_weight_unit: 'kg',
    body_weight_hint: 'Dùng để tính toán mục tiêu carbohydrate theo công thức allometric (cân nặng^0.75).',
    body_experience:  'Trình Độ Kinh Nghiệm',
    body_beginner:    'Người Mới',
    body_beginner_desc:     'Cuộc đua đầu tiên hoặc thứ hai',
    body_intermediate:      'Trung Cấp',
    body_intermediate_desc: '1–3 năm thi đấu',
    body_advanced:          'Nâng Cao',
    body_advanced_desc:     '3+ năm, thi đấu thường xuyên',

    // ── StepSweat ─────────────────────────────────────────────────────────────
    sweat_title:    'Hồ Sơ Mồ Hôi',
    sweat_subtitle: 'Đây là phần cá nhân hoá nhất trong kế hoạch. Tốc độ mồ hôi và độ mặn xác định nhu cầu nước và natri.',
    sweat_analogy:  ' Hãy nghĩ như đồng hồ xăng xe — chúng tôi cần biết bình của bạn hao nhanh cỡ nào.',
    sweat_test_title: '🧪 Bạn có dữ liệu xét nghiệm mồ hôi không?',
    sweat_test_desc:  'Nếu bạn đã làm xét nghiệm mồ hôi (qua Precision Hydration, lab...), nhập số liệu chính xác để có kế hoạch chính xác hơn.',
    sweat_test_btn:    'Nhập dữ liệu xét nghiệm',
    sweat_test_active: '✓ Đang dùng dữ liệu xét nghiệm',
    sweat_rate_label:  'Tốc Độ Mồ Hôi',
    sweat_rate_unit:   'ml / giờ',
    sweat_rate_hint:   'Đo bằng cân nặng mất mỗi giờ tập (vd: 1.2 kg/giờ = 1200 ml/giờ)',
    sweat_sodium_label:'Nồng Độ Natri Trong Mồ Hôi',
    sweat_sodium_unit: 'mg / L',
    sweat_sodium_hint: 'Từ miếng dán mồ hôi hoặc xét nghiệm lab. Phạm vi thông thường: 400–1800 mg/L.',
    sweat_override:    '· bị ghi đè bởi dữ liệu xét nghiệm',
    sweat_level_q:   'Bạn thường đổ mồ hôi như thế nào?',
    sweat_salt_q:    'Lượng muối bạn mất đi như thế nào? (cặn trắng trên da hoặc quần áo)',
    sweat_fuel_q:    'Bạn muốn dùng sản phẩm dinh dưỡng theo tỉ lệ nào?',
    fuel_gel_label:  'Gel',
    fuel_gel_desc:   'Gần 100% dạng Gel/Kẹo',
    fuel_mix_label:  'Mix (Gel và Bột Năng Lượng)',
    fuel_mix_desc:   'Kết hợp cân bằng',
    fuel_liquid_label: 'Bột năng lượng',
    fuel_liquid_desc:  'Ưu tiên uống calo lỏng',
    sweat_temp_q:    'Nhiệt độ dự kiến ngày đua',
    sweat_low:       'Ít mồ hôi',        sweat_low_desc:      'Gần như không thấy mồ hôi dù trời nóng',
    sweat_medium:    'Mồ hôi vừa',       sweat_medium_desc:   'Thấy mồ hôi, ướt nhẹ',
    sweat_high:      'Ra nhiều mồ hôi',  sweat_high_desc:     'Mồ hôi nhỏ giọt, áo ướt đẫm',
    sweat_very_high: 'Ra rất nhiều mồ hôi', sweat_very_high_desc:'Mồ hôi chảy thành vũng',
    salt_low:        'Ít/không có cặn',  salt_low_desc:       'Không có vệt trắng trên da hoặc quần áo',
    salt_medium:     'Vài vệt trắng',    salt_medium_desc:    'Cặn muối nhạt sau các buổi dài',
    salt_high:       'Cặn muối nhiều',   salt_high_desc:      'Lớp vỏ trắng rõ trên da sau khi đổ mồ hôi',
    salt_very_high:  'Rất mặn',          salt_very_high_desc: 'Cay mắt, lớp vỏ trắng dày khắp nơi',

    // Temperature
    temp_cold: '< 10°C', desc_cold: 'Rất lạnh',
    temp_cool: '10–15°C', desc_cool: 'Mát mẻ',
    temp_mild: '15–20°C', desc_mild: 'Mát mẻ / Ôn hòa',
    temp_warm: '20–25°C', desc_warm: 'Ấm áp',
    temp_hot: '25–30°C', desc_hot: 'Nóng',
    temp_very_hot: '> 30°C', desc_very_hot: 'Rất nóng',

    sweat_test_success_1: 'Kế hoạch sẽ dùng',
    sweat_test_success_2: 'ml/h tốc độ mồ hôi và',
    sweat_test_success_3: 'mg/L natri.',


    // ── StepContact ───────────────────────────────────────────────────────────
    contact_title:    'Nhận Kế Hoạch Của Bạn',
    contact_subtitle: 'Điền thông tin để nhận kế hoạch dinh dưỡng cá nhân hoá. Dữ liệu chỉ dùng để liên hệ hỗ trợ, không chia sẻ bên thứ ba.',
    contact_lastname:   'Họ',
    contact_firstname:  'Tên',
    contact_email:      'Email',
    contact_phone:      'Số Điện Thoại',
    contact_optional:   'Không bắt buộc',
    contact_privacy:    '🔒 Thông tin của bạn được bảo mật và chỉ dùng để cung cấp kế hoạch dinh dưỡng từ HiBoost.',
    contact_submit:     '🚀 Tạo Kế Hoạch →',
    contact_loading:    '⏳ Đang tính toán...',
    contact_err_last:   'Vui lòng nhập họ',
    contact_err_first:  'Vui lòng nhập tên',
    contact_err_email:  'Vui lòng nhập email',
    contact_err_email2: 'Email không hợp lệ',
    contact_err_phone:  'Số điện thoại không hợp lệ',

    // ── Results ───────────────────────────────────────────────────────────────
    results_subtitle:   'KẾ HOẠCH ĐUA CÁ NHÂN CỦA BẠN',
    results_new:        '↩ Kế Hoạch Mới',
    results_carbs_hr:   'Carbs / giờ',
    results_sodium_hr:  'Natri / giờ',
    results_fluid_hr:   'Nước / giờ',
    results_sweat_hr:   'Mồ hôi / giờ',
    results_estimated:  'ước tính',
    results_from_test:  '🧪 từ xét nghiệm của bạn',
    results_segment:    '🏁 Phân Tích Dinh Dưỡng Theo Đoạn',
    results_segment_sub:'Mục tiêu dinh dưỡng cho từng phần đua.',
    results_no_fuel:    'Không cần nạp năng lượng',
    results_timeline:   '⏱ Lịch Trình Đua',
    results_timeline_sub:'Các mốc theo phân đoạn — khi nào và uống/ăn gì.',
    results_products:   '🛒 Sản Phẩm Được Đề Xuất',
    results_products_sub:'Từ danh mục HiBoost, phù hợp với kế hoạch của bạn.',
    results_no_products:'Buổi ngắn — chỉ cần nước, không cần sản phẩm.',
    results_tips:       '💡 Lời Khuyên Chính Cho Kế Hoạch',
    results_cta_title:  'Sẵn sàng thi đấu?',
    results_cta_desc:   'Mua tất cả sản phẩm đề xuất tại HiBoost Nutrition.',
    results_cta_btn:    'Mua Ngay →',
    results_high_sodium_title: 'Cảnh Báo Lượng Muối:',
    results_high_sodium_desc: 'Mục tiêu nạp Natri (Sodium) của bạn đang ở mức rất cao (>1000mg/h). Việc uống một lượng nước quá mặn liên tục trong nhiều giờ có thể gây rối loạn tiêu hoá. Hãy chủ động train dạ dày trong các bài tập dài, hoặc kết hợp dùng nước uống điện giải cùng muối viên (Salt caps) để cân bằng vị giác.',
    results_disclaimer: '⚠️ Kế hoạch được tạo dựa trên công thức khoa học thể thao trung bình. Nhu cầu cá nhân có thể khác nhau. Luôn thử nghiệm dinh dưỡng trong tập luyện trước ngày đua. Tham khảo chuyên gia dinh dưỡng thể thao cho hướng dẫn chuyên sâu.',
    results_total:      'tổng',
    nf_title:           'Thông Tin Dinh Dưỡng',
    nf_per_serving:     'mỗi khẩu phần',
    nf_calories:        'Calo',
    nf_carbs:           'Carbs',
    nf_sodium:          'Natri',
    nf_potassium:       'Kali',
    nf_caffeine:        'Caffeine',

    // Cheat Sheet / Strategy Sticker
    sticker_title:      'Strategy Sticker',
    sticker_desc:       'Tải ảnh Tóm tắt nhanh Kế hoạch nạp để dán lên Ghi-đông (Top Tube) khi đi thi đấu.',
    sticker_time:       'THỜI GIAN',
    sticker_nutrition:  'DINH DƯỠNG',
    sticker_finish:     'HOÀN THÀNH ĐẠP',
    sticker_download:   '⬇️ Tải file PNG',

    // Cart / E-commerce
    cart_subtotal:      'Tổng tiền tạm tính:',
    cart_order_btn:     '🛒 Yêu Cầu Đặt Hàng & Tư Vấn',
    cart_sending:       '⏳ Đang gửi yêu cầu...',
    cart_success:       '✅ Yêu cầu đã được gửi lên hệ thống Hiboost CRM. Nhân viên chúng tôi sẽ gọi điện xác nhận ưu đãi và lên đơn cho bạn!',

    // Usage keys
    usage_maurten_320:  'Pha 1 gói (80g carbs) vào 500ml. Uống từ từ mỗi 15 phút. Nguồn hydrogel hạn chế tức bụng.',
    usage_ph_powder:    'Pha 1 gói cho 500ml nước. Cấp nước và điện giải liên tục.',
    usage_ph_gel:       'Ăn 1 gel mỗi {interval} phút. Không nạp cùng lúc với lúc uống Maurten 320.',
    usage_ph_gel_caf:   'Dành riêng cho 1/3 quãng đường cuối. Tối đa 2–3 gói mỗi sự kiện.',
    usage_pf90:         'Túi 90g Carbs cho đạp xe. 1 túi dùng trong ~1.5 giờ ở mức 60g/h.',
    usage_salt_caps:    'Uống 1–2 viên kèm nước mỗi 30–45 phút.',
    usage_maurten_gel:  'Dòng Gel Hydrogel cao cấp. Dùng 1 gói mỗi {interval} phút.',

    // Splits
    split_swim: 'Bơi',
    split_t1:   'T1 (Chuyển tiếp)',
    split_bike: 'Đạp xe',
    split_t2:   'T2 (Chuyển tiếp)',
    split_run:  'Chạy bộ',

    // Tips keys from nutrition engine
    tip_female_fat_ox: 'VĐV Nữ: hormone oestrogen thúc đẩy quá trình đốt mỡ — bạn có thể dung nạp lượng carb thấp hơn một chút so với VĐV nam ở cùng cường độ.',
    tip_female_cycle: 'Chu kỳ nội tiết có thể ảnh hưởng đến khả năng chịu nhiệt và giữ nước. Hãy theo dõi dinh dưỡng trong quá trình luyện tập qua các chu kỳ kinh nguyệt của bạn.',
    tip_youth_growth: 'VĐV Trẻ: cơ thể bạn cần nhiều carb hơn theo tỷ lệ trọng lượng. Đừng nạp thiếu năng lượng — sự phát triển và phục hồi phụ thuộc vào việc nạp đủ năng lượng.',
    tip_masters_recovery: 'VĐV Masters (35–49): Ưu tiên dinh dưỡng phục hồi với protein trong vòng 30 phút sau khi kết thúc. Sự hấp thu carb tương đương nhưng quá trình phục hồi ở cơ bắp sẽ chậm hơn.',
    tip_senior_electrolytes: 'VĐV 50+: Điện giải trở nên cực kỳ quan trọng — thận hoạt động kém hiệu quả hơn trong việc giữ natri. Không nên bỏ qua viên uống điện giải (salt capsules).',
    tip_senior_protein: 'Nạp protein sau cuộc đua rát quan trọng với các VĐV lớn tuổi. Hãy hướng tới 30–40g protein trong vòng 1-2 giờ sau khi kết thúc.',
    tip_short_effort: 'Dưới 45 phút — chỉ cần uống nước lọc là đủ. Không cần nạp thêm Carbs.',
    tip_high_carb_gut: 'Mục tiêu Carb ở mức cao: Hãy liên tục luyện tập để dạ dày (Gut) quen với việc nạp vào trong các buổi tập dài (Long runs/rides) nhằm tránh vấn đề về tiêu hoá (GI) ở ngày đua.',
    tip_high_carb_mix: 'Nên kết hợp sử dụng nhiều nguồn Carb (pha trộn Glucose + Fructose) để cơ thể hấp thu tốt hơn khi mục tiêu nạp vượt mức 60g/giờ.',
    tip_salty_sweater: 'Mục tiêu muối (Sodium) rất cao: Cơ thể bạn vã ra cực kì mặn khi đổ mồ hôi. Đừng bao giờ bỏ qua điện giải ngay cả trong những buổi chạy/đạp có cự ly ngắn.',
    tip_hot_conditions: 'Nhiệt độ ngày đua khá Nóng: Khuyến nghị hãy bắt đầu nạp nước trước 2 giờ (pre-load) cuộc đua với 500ml Nước làm đồ uống + hỗn hợp chất điện giải mạnh.',
    tip_pre_cooling: 'Nghiên cứu thêm chiến lược làm mát trước khi đua (Áo phao đá, Khăn ướp băng) có thể cải thiện hiệu suất rõ rệt trong thời tiết nắng rát/độ ẩm đặc này.',
    tip_carb_load: 'Dành cho các cự ly đua lớn hơn 3 tiếng (Endurance): Bắt buộc nạp dự trữ tinh bột / bột đường (Carb-loading) trước 2 ngày sự kiện diễn ra.',
    tip_practice_full: 'Bạn mới làm quen dinh dưỡng? Hãy test toàn bộ kế hoạch trên trong ít nhất 2 buổi tập dài trước khi bước vào cuộc đua chính thức.',
    tip_beginner_conservative: 'Bạn mới làm quen dinh dưỡng thi đấu? Hãy bắt đầu thật chậm và chắc chắn, thử dùng lượng Carb ít (ví dụ bằng nửa mục tiêu), nghe cảm nhận cơ thể rồi tăng dần.',

    // Footer
    footer: 'Dựa trên hướng dẫn khoa học thể thao ACSM & ISSN',
  },
};
